spring.application.name=reliable-job-queue
# Use a file-based H2 database path so data survives service restarts
spring.datasource.url=jdbc:h2:file:./data/queue_db;DB_CLOSE_DELAY=-1
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
# Automatically update the database schema matching our entities
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true

# Retry Delay
queue.retry.linear-delay=10
queue.retry.exponential-base=2

#Lease time
queue.lease-duration=30
queue.heartbeat-interval=10

#poll-delay time
queue.poll-delay=1000